### PR TITLE
Super lu

### PR DESCRIPTION
**Pull request by etpalmer63**
I tried to change "SuperLU" to "SuperLu" everywhere where it seemed appropriate.

### CODE REVIEW

**Comment by xiaoyeli** [comment]
@etpalmer63 
SuperLU is correct as is (not SuperLu).  Strumpack need to be changed to STRUMPACK.
I think the one needs correction is MueLu (instead of MueLU), see their users guide:
https://trilinos.github.io/pdfs/mueluguide.pdf

**Comment by etpalmer63** [comment]
Ah, thank you for the correction! @xiaoyeli, I think I got it wrong in the agenda too. -- Fix coming shortly.

**Comment by xiaoyeli** [comment]
Hi Erik,

SuperLU is correct as is (not SuperLu).  Strumpack need to be changed to
STRUMPACK.
I think the one needs correction is MueLu, see their users guide:
https://trilinos.github.io/pdfs/mueluguide.pdf

Thanks.
Sherry

**Comment by etpalmer63** [comment]
Hi Sherry, 

I took a look through the git branch that should appear on the web pages (gh-pages) and I didn't see a place where SuperLU, STRUMPACK or MueLu needed to be changed. However I maybe overlooking something. Can you point me toward the place on the web page where it needs to fixed? 

Thanks,

Erik

**Comment by xiaoyeli** [comment]
Hi Erik,
What is the link again?  I think they were all corrected before the training

**Comment by etpalmer63** [comment]
Hi Sherry,

The link to the website is here,
https://xsdk-project.github.io/MathPackagesTraining2022/. I also think they
all got corrected, however please let me know if you notice anything.

Thanks,

Erik

**Comment by xiaoyeli** [comment]
Erik,

I just checked, they all look good now.
Thanks.

**Pull request closed without merging**
